apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisclient
  labels:
    app: redisclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisclient
  template:
    metadata:
      labels:
        app: redisclient
    spec:
      containers:
        - name: redisclient
          image: redisclient
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_PROFILES_ACTIVE
              value: local
